version: "3.8"
services:
  mongo:
    image: mongo:5.0.9
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./database/mongodb/db:/data/db
    command: [--auth]

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mexpress
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: always
    ports:
      - "8081:8081"
    
