// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	domain "api/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"

	r "api/utils/r"
)

// VisitedRepository is an autogenerated mock type for the VisitedRepository type
type VisitedRepository struct {
	mock.Mock
}

// Add provides a mock function with given fields: ctx, d
func (_m *VisitedRepository) Add(ctx context.Context, d *domain.Visited) (primitive.ObjectID, r.Ex) {
	ret := _m.Called(ctx, d)

	var r0 primitive.ObjectID
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Visited) primitive.ObjectID); ok {
		r0 = rf(ctx, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(primitive.ObjectID)
		}
	}

	var r1 r.Ex
	if rf, ok := ret.Get(1).(func(context.Context, *domain.Visited) r.Ex); ok {
		r1 = rf(ctx, d)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(r.Ex)
		}
	}

	return r0, r1
}

// DeleteByID provides a mock function with given fields: ctx, ID
func (_m *VisitedRepository) DeleteByID(ctx context.Context, ID primitive.ObjectID) r.Ex {
	ret := _m.Called(ctx, ID)

	var r0 r.Ex
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) r.Ex); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(r.Ex)
		}
	}

	return r0
}

// FetchAll provides a mock function with given fields: ctx
func (_m *VisitedRepository) FetchAll(ctx context.Context) ([]*domain.Visited, r.Ex) {
	ret := _m.Called(ctx)

	var r0 []*domain.Visited
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Visited); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Visited)
		}
	}

	var r1 r.Ex
	if rf, ok := ret.Get(1).(func(context.Context) r.Ex); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(r.Ex)
		}
	}

	return r0, r1
}

// FetchByID provides a mock function with given fields: ctx, ID
func (_m *VisitedRepository) FetchByID(ctx context.Context, ID primitive.ObjectID) (*domain.Visited, r.Ex) {
	ret := _m.Called(ctx, ID)

	var r0 *domain.Visited
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) *domain.Visited); ok {
		r0 = rf(ctx, ID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Visited)
		}
	}

	var r1 r.Ex
	if rf, ok := ret.Get(1).(func(context.Context, primitive.ObjectID) r.Ex); ok {
		r1 = rf(ctx, ID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(r.Ex)
		}
	}

	return r0, r1
}

// UpdateByID provides a mock function with given fields: ctx, ID, d
func (_m *VisitedRepository) UpdateByID(ctx context.Context, ID primitive.ObjectID, d *domain.Visited) r.Ex {
	ret := _m.Called(ctx, ID, d)

	var r0 r.Ex
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID, *domain.Visited) r.Ex); ok {
		r0 = rf(ctx, ID, d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(r.Ex)
		}
	}

	return r0
}

type mockConstructorTestingTNewVisitedRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewVisitedRepository creates a new instance of VisitedRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewVisitedRepository(t mockConstructorTestingTNewVisitedRepository) *VisitedRepository {
	mock := &VisitedRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
